### PR TITLE
Add parentheses cheat sheet

### PR DESCRIPTION
**Pull request by nerdinand**
Screenshot 2020-01-20 at 19 19 22

### CODE REVIEW

**Comment by nerdinand** [comment]
@lxxxvi yeah, you're right. I can change it for `{ }`, but for `< >`, the hash rocket is exactly the point... ;P

**Comment by lxxxvi** [comment]
> @lxxxvi yeah, you're right. I can change it for `{ }`, but for `< >`, the hash rocket is exactly the point... ;P

Yeah, may be add a comment to the example in section `< >` that says something like `old-school`, and use the new-school syntax for the others...?

**Comment by lxxxvi** [comment]
I totally agree with @hharen, especially...

>     * changing def m(x) to def my_method(x), method call my_method(42) - for a lot of beginners all these one-letter names can confusing

**Comment by nerdinand** [comment]
Now looks like this:
Screenshot 2020-01-27 at 16 46 30

**Comment by hharen** [comment]
Perfect ;)

**Pull request merged**
